### ISSUE TITLE
Can't catch this

### ISSUE THREAD

**Issue by RiniceSiberia** [csense-oss/idea-kotlin-checked-exceptions#35] opened 2024-07-18 08:57 UTC
![image](https://github.com/user-attachments/assets/eca0aec9-ffd2-42eb-8ed9-8c52e1960c42)
as shown in the picture

**Comment by minjerd-riis** [comment] 2024-08-15 13:54
I'm seeing the same issue with `Regex.find()`. It says `kotlin.IndexOutOfBoundsException` is uncaught but it clearly is.
If I catch the `RuntimeException` superclass from either `kotlin` or `java.lang`, the warning goes away.

![image](https://github.com/user-attachments/assets/4c76184b-df01-4367-b283-8a737635b3a7)

**Comment by Tvede-dk** [comment] 2024-08-24 15:11
Thanks both @RiniceSiberia & @minjerd-riis , 
The issue is based on how the kotlin plugin "resolves" classes, which sometimes gets pretty bad / difficult. I might have a  fix for some of this in the next version, as the code for resolving classes had to be redone as with idea 2024.2 (and forward) Jetbrains changed the inner workings & the API :)

**Comment by Tvede-dk** [comment] 2024-09-13 08:06
should be fixed in 2.2.0

**Closed by Tvede-dk** 2024-09-13 08:06 UTC
